compression:
  method: zstd
  level: 6

buffers:
  input: 128Kb
  framing: 256Kb

files:
  root: /home/emacs/Tmp/data
  name: /${dir}/${name}-${time | %Y.%m.%d-%H }.zst
  rotation: /${dir}/${name}-${time | %Y.%m.%d-%H:%M }.zst
  notify:
    type: file
    path: /home/emacs/Tmp/rotated_files

links:
  root: /home/emacs/Tmp/logs
  name: /${dir}/${name}.zst
  rotation: /${dir}/${name}-${time | %Y.%m.%d-%H:%M }.zst

logrotate:
  method: periodic
  schedule: "*/1 * * * *"
